### PR TITLE
dev: make file watching friendly

### PR DESCRIPTION
**Pull request by Myriad-Dreamin**

### CODE REVIEW

**Comment by QuarticCat** [comment]
LGTM. I'm not familiar with the codebase so I only checked that the new implementation should effectively do the same thing.

**Comment by QuarticCat** [comment]
Observed performance regression with tinymist on my machine (2.7s -> 3.0s). Need to investigate.

**Comment by Myriad-Dreamin** [comment]
```
 hyperfine.exe ' .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log' ' .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log'
Benchmark 1:  .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.278 s ±  0.039 s    [User: 0.087 s, System: 0.027 s]
  Range (min … max):    2.230 s …  2.363 s    10 runs

Benchmark 2:  .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.341 s ±  0.047 s    [User: 0.143 s, System: 0.036 s]
  Range (min … max):    2.255 s …  2.413 s    10 runs

Summary
   .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log ran
    1.03 ± 0.03 times faster than  .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
```

Swapped

```
hyperfine.exe ' .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log' ' .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log'
Benchmark 1:  .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.361 s ±  0.044 s    [User: 0.094 s, System: 0.050 s]
  Range (min … max):    2.291 s …  2.416 s    10 runs

Benchmark 2:  .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.298 s ±  0.066 s    [User: 0.148 s, System: 0.064 s]
  Range (min … max):    2.244 s …  2.475 s    10 runs

Summary
   .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log ran
    1.03 ± 0.04 times faster than  .\target\release\tinymist lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
```

**Comment by Myriad-Dreamin** [comment]
judgement: `tinymist-watch-new` (commit d52b9bd, dev: more friendly file watching) triggers more compilations (around 1030 times) by sending fake removes (`changeset.removes.push(path.clone());`), than rest four tinymist variants (around 750 times).

The variants are described as following:
- old: without this PR.
- watch-new: after applied commit d52b9bd, dev: more friendly file watching
- no-watch: let notify actor ignore all events.
- defer-delete: after applied [dev: avoid sending fake remove events](https://github.com/Myriad-Dreamin/typst.ts/pull/522/commits/16792a37a8a03590ae68ba8baa139822df7cfe4b)
- no-removes: simply change the retainer based on [dev: avoid sending fake remove events](https://github.com/Myriad-Dreamin/typst.ts/pull/522/commits/16792a37a8a03590ae68ba8baa139822df7cfe4b) to get rid of `changeset.removes.push(path.clone());`
  ```patch
  - self.watched_entries.retain(|path, entry| {
  -     if !entry.seen && entry.watching {
  -         log::debug!("unwatch {path:?}");
  -         if let Some(watcher) = &mut self.watcher {
  -             log_notify_error(watcher.0.unwatch(path), "failed to unwatch");
  -             entry.watching = false;
  -         }
  -     }
  - 
  -     let fresh = self.lifetime - entry.lifetime < 30;
  -     if !fresh {
  -         changeset.removes.push(path.clone());
  -     }
  -     fresh
  - });
  + self.watched_entries.retain(|path, entry| entry.seen);
  ```

```
Benchmark 1: .\target\release\tinymist-no-watch lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.229 s ±  0.056 s    [User: 0.308 s, System: 0.204 s]
  Range (min … max):    2.137 s …  2.339 s    10 runs

Benchmark 2: .\target\release\tinymist-watch-defer-delete lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.157 s ±  0.040 s    [User: 0.022 s, System: 0.009 s]
  Range (min … max):    2.090 s …  2.237 s    10 runs

Benchmark 3:  .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.272 s ±  0.049 s    [User: 0.002 s, System: 0.017 s]
  Range (min … max):    2.225 s …  2.365 s    10 runs

Benchmark 4: .\target\release\tinymist-watch-new lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.301 s ±  0.047 s    [User: 0.017 s, System: 0.012 s]
  Range (min … max):    2.224 s …  2.349 s    10 runs

Benchmark 5: .\target\release\tinymist-no-removes lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
  Time (mean ± σ):      2.251 s ±  0.036 s    [User: 0.029 s, System: 0.009 s]
  Range (min … max):    2.193 s …  2.307 s    10 runs

Summary
  .\target\release\tinymist-watch-defer-delete lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log ran
    1.03 ± 0.03 times faster than .\target\release\tinymist-no-watch lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
    1.04 ± 0.03 times faster than .\target\release\tinymist-no-removes lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
    1.05 ± 0.03 times faster than  .\target\release\tinymist-old lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
    1.07 ± 0.03 times faster than .\target\release\tinymist-watch-new lsp --replay .\target\e2e\tinymist\vscode\mirror.log 2> .\local\error.log > .\local\output.log
```

**Pull request merged**
